// lib/presentation/onboarding/localization/app_localizations.dart

import 'package:flutter/material.dart';

extension AppLocalizationsX on BuildContext {
  String tr(String key) => AppLocalizations.get(key, Localizations.localeOf(this).languageCode);
}

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'CropCare',
      'splash_subtitle': 'Smart Crop Health Assistant',
      'onboarding_title_1': 'Identify the Problem',
      'onboarding_desc_1':
          'Capture photos to detect crop diseases early and accurately.',
      'onboarding_title_2': 'Get Clear Guidance',
      'onboarding_desc_2':
          'Receive clear treatment instructions in your own language.',
      'onboarding_title_3': 'Expert Escalation',
      'onboarding_desc_3':
          'Get in touch with human agronomists when the AI is uncertain.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'select_language_title': 'Select Your Language',
      'select_language_subtitle':
          'Choose your preferred language for CropCare',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'Confirm',
      'home_title': 'CropCare Home',
      'home_welcome': 'Welcome to CropCare!',
      'home_subtitle': 'Detect crop diseases and get treatment advice instantly.',
      'change_language': 'Change Language',
      'select_crop_title': 'Select Crop',
      'select_crop_subtitle': 'Choose the crop you want to scan',
      'camera_permission_title': 'Camera Permission Required',
      'camera_permission_desc':
          'CropCare needs access to your camera to take photos for disease detection.',
      'open_app_settings': 'Open App Settings',
      'grant_permission': 'Grant Permission',
      'capture_photo': 'Take Photo',
      'review_photo_title': 'Review Photo',
      'retake': 'Retake',
      'use_photo': 'Use Photo',
      'scan_result_title': 'Scan Details',
      'scan_id': 'Scan ID',
      'crop': 'Crop',
      'image_path': 'Image Path',
      'status': 'Status',
      'captured_at': 'Captured At',
      'settings_title': 'Settings',
      'section_language': 'Language',
      'section_accessibility': 'Accessibility',
      'section_notifications': 'Notifications',
      'section_offline_data': 'Offline Data & Sync',
      'coming_soon': 'Coming Soon',
      'coming_soon_desc': 'This section will be available in a future update.',
      'start_scan': 'Scan Crop',
      'diagnosis_result_title': 'Diagnosis Result',
      'treatment_guidance_title': 'Treatment Guidance',
      'treatment_summary': 'Summary',
      'treatment_what_to_do': 'What to Do',
      'treatment_what_to_avoid': 'What to Avoid',
      'recheck_after_days': 'Recheck in',
      'days': 'days',
      'treatment_source_llm': 'AI Generated Advice',
      'treatment_source_ai': 'AI',
      'treatment_source_offline': 'On-Device Offline',
      'offline_guideline_badge': 'On-Device Offline',
      'treatment_observations_label': 'Add Your Observations (Optional)',
      'treatment_observations_hint':
          'e.g. Started 3 days ago, leaves yellowing at bottom, heavy rain recently...',
      'get_treatment_btn': 'Get AI Recommendation',
      'offline_connection_msg':
          'Unable to reach CropCare AI. Please verify your internet or Wi-Fi connection.',
      'retry_btn': 'Retry Now',
      'healthy_crop_msg':
          'Your plant appears healthy! Keep up your current crop management practices.',
      'ai_disclaimer':
          'AI-assisted prediction — verify before applying chemical treatments.',
      'scan_again': 'Scan Again',
      'get_expert_help': 'WhatsApp Share with Expert',
      'disease_detected': 'Identified Disease',
      'confidence': 'Confidence',
      'severity': 'Severity',
      'fetching_treatment': 'Consulting AI Agronomist...',
      'low_confidence_advisory':
          'Low confidence AI result (<80%). We suggest consulting an agricultural expert via WhatsApp.',
      'escalation_title': 'Escalate to Expert',
      'escalation_subtitle':
          'Share the leaf photo and diagnosis details with an expert on WhatsApp',
      'farmer_notes_label': 'Your Observations for the Expert',
      'farmer_notes_hint':
          'e.g., Field location, duration of symptoms, fertilizer applied...',
      'share_whatsapp_btn': 'WhatsApp Share with Expert',
      'scan_history_title': 'Scan History',
      'scan_history_empty':
          'No scans yet. Tap "Scan Crop" above to start your first diagnosis!',
      'filter_all': 'All Scans',
      'filter_low_conf': 'Low Confidence (<80%)',
      'filter_shared': 'Shared with Expert',
      'filter_healthy': 'Healthy Crops',
      'filter_date_today': 'Scanned Today',
      'filter_date_week': 'Scanned This Week',
      'filter_date_month': 'Scanned This Month',
      'filter_crop_tomato': 'Crop: Tomato',
      'filter_crop_chili': 'Crop: Chili',
      'filter_crop_paddy': 'Crop: Paddy',
      'filter_crop_corn': 'Crop: Corn',
      'filter_crop_potato': 'Crop: Potato',
      'export_btn': 'Export',
      'scans_count': 'scans',
      'auth_title': 'Account & Sign In',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'email': 'Email Address',
      'password': 'Password',
      'link_guest_account': 'Link this device\'s scan history to your account',
      'guest_badge': 'Guest Mode',
      'link_account_btn': 'Link Account',
      'signed_in_as': 'Signed in as',
      'sign_out': 'Sign Out',
      'email_invalid': 'Please enter a valid email address',
      'password_short': 'Password must be at least 6 characters',
      'account_section': 'Account',
      'account_guest_desc': 'You are browsing as a guest. Create an account to sync scans across devices.',
      'read_aloud': 'Read Aloud',
      'stop_reading': 'Stop Audio',
      'playing_audio': 'Playing Audio...',
      'sync_now': 'Sync Now',
      'sync_pending': 'pending to sync',
      'sync_in_progress': 'Syncing data to cloud...',
      'sync_success': 'All data synchronized with cloud',
      'sync_offline_ready': 'Offline Ready',
      'auth_method_email': 'Email',
      'auth_method_phone': 'Phone',
      'phone_number': 'Phone Number',
      'phone_invalid': 'Please enter a valid phone number (e.g. +94771234567)',
      'otp_entry_title': 'Enter Verification Code',
      'otp_code_label': '6-Digit Code',
      'otp_submit': 'Verify & Continue',
      'otp_resend': 'Resend Code',
      'otp_resend_in': 'Resend code in {n}s',
      'otp_expired': 'Verification code expired. Please request a new code.',
      'otp_wrong_code': 'Invalid verification code. Please check and try again.',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'forgot_password_subtitle':
          'Enter your registered email address to receive password reset instructions.',
      'send_reset_link': 'Send Reset Instructions',
      'reset_link_sent_title': 'Reset Email Sent',
      'reset_link_sent_desc':
          'If an account exists with this email, password reset instructions have been sent. Please check your inbox and spam folder.',
      'back_to_sign_in': 'Back to Sign In',
      'consent_agreement_prefix': 'By creating an account, you agree to our',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'and_connector': 'and',
      'section_help_faq': 'Help & FAQ',
      'section_terms_privacy': 'Terms & Privacy Policy',
      'faq_title': 'Frequently Asked Questions',
      'faq_category_scanning': 'Scanning & Diagnosis',
      'faq_q1': 'How does crop disease detection work?',
      'faq_a1':
          'CropCare uses on-device AI models to analyze leaf photos directly on your phone. When connected, an AI agronomist provides detailed treatment advice.',
      'faq_q2': 'Can I use CropCare without an Internet connection?',
      'faq_a2':
          'Yes! Crop disease detection and offline treatment guidelines work completely offline. Scans are saved on your device and sync when you reconnect.',
      'faq_q3': 'What should I do if the diagnosis confidence is low?',
      'faq_a3':
          'When confidence is below 80%, CropCare allows you to escalate the scan directly to an agricultural expert via WhatsApp with your notes and photo.',
      'faq_category_account_sync': 'Account & Cloud Sync',
      'faq_q4': 'Do I need to create an account?',
      'faq_a4':
          'No. You can use CropCare in Guest Mode. Creating an account lets you back up and sync your scan history across multiple devices.',
      'faq_q5': 'How does cloud sync work?',
      'faq_a5':
          'When online, tap "Sync Now" in Settings or let CropCare automatically sync pending scans in the background.',
      'terms_privacy_title': 'Terms & Privacy Policy',
      'terms_tab': 'Terms of Service',
      'privacy_tab': 'Privacy Policy',
      'terms_content_title': 'CropCare Terms of Service',
      'terms_content_body':
          '1. Purpose\nCropCare is an AI-powered advisory tool designed to assist farmers in early disease detection. It does not replace professional agronomist advice.\n\n2. AI Accuracy & Advice\nDiagnosis results are probabilistic. Always verify chemical treatments with local agricultural extension officers before application.\n\n3. User Conduct\nYou agree to capture relevant plant leaf images and not misuse the cloud sync or WhatsApp escalation features.',
      'privacy_content_title': 'CropCare Privacy Policy',
      'privacy_content_body':
          '1. Data Collection\nWe only collect crop photos you capture, diagnosis history, and account identifiers (email or phone number) if you choose to sign up.\n\n2. Local-First Processing\nYour scan history is stored locally on your device in an offline database. Data is only transmitted to the cloud when you choose to synchronize.\n\n3. No Third-Party Selling\nWe never sell your personal data, farm location, or scan history to third parties.',
      'pick_from_gallery': 'Choose from Gallery',
      'gallery_button_label': 'Gallery',
      'export_data_title': 'Export Scan History',
      'export_data_desc':
          'Download or share a CSV copy of all your local scans.',
      'export_data_empty': 'No scans found to export.',
      'export_data_success': 'Scan history exported successfully.',
      'export_data_btn': 'Export',
      'section_profile': 'Profile & Account',
      'section_preferences': 'Preferences',
      'section_data_storage': 'Data & Storage',
      'section_support_legal': 'Support & Legal',
      'app_version': 'App Version',
      'profile_title': 'User Profile',
      'profile_account_info': 'Account Information',
      'profile_account_type': 'Account Type',
      'profile_registered_user': 'Registered Account',
      'profile_user_id': 'User ID',
      'change_email': 'Change Email',
      'enter_new_email': 'Enter new email address',
      'change_phone': 'Change Phone Number',
      'enter_new_phone': 'Enter new phone number (e.g. +94771234567)',
      'verify_new_phone': 'Verify New Phone',
      'send_code': 'Send Code',
      'save_changes': 'Save',
      'delete_account': 'Delete Account',
      'delete_account_desc':
          'Permanently delete your account and cloud sync data.',
      'delete_account_confirm_title': 'Delete Account?',
      'delete_account_confirm_desc':
          'This action cannot be undone. Your remote account and synchronized cloud data will be permanently removed.',
      'delete_account_action': 'Yes, Delete My Account',
      'delete_account_success': 'Your account has been deleted.',
      'cancel': 'Cancel',
      'send_feedback': 'Send Feedback',
      'feedback_title': 'Feedback & Suggestions',
      'feedback_subtitle':
          'Help us improve CropCare. Share your thoughts, report issues, or suggest new features.',
      'feedback_category': 'Category',
      'category_general': 'General Feedback',
      'category_bug': 'Report a Bug / Issue',
      'category_suggestion': 'Feature Suggestion',
      'feedback_hint': 'Type your feedback or comments here...',
      'feedback_submit': 'Submit Feedback',
      'feedback_success': 'Thank you! Your feedback has been received.',
      'feedback_empty_error': 'Please enter a message before submitting.',
      'cancel_scan': 'Cancel Scan',
      'copy_summary_btn': 'Copy Summary',
      'summary_copied': 'Diagnosis summary copied to clipboard.',
      'share_other_apps': 'Share via Other Apps',
      'view_profile': 'View Profile',
      'back_to_home': 'Back to Home',
      'low_confidence_badge': 'Low Confidence Match',
      'add_photo_title': 'New Scan',
      'add_photo_subtitle': 'Take a photo of the affected plant or select from gallery for AI disease diagnosis.',
      'take_photo_btn': 'Take Photo',
      'take_photo_desc': 'Use camera to scan leaf',
      'choose_gallery_btn': 'Choose from Gallery',
      'choose_gallery_desc': 'Upload from photo library',
      'supported_crops_label': 'Supported Crops',
      'supported_crops_desc': 'AI model is trained to recognize diseases on these crops:',
      'gallery_permission_denied_title': 'Gallery Permission Required',
      'gallery_permission_denied_desc': 'Please grant gallery access in App Settings to select images.',
      'unknown_crop': 'Unknown Crop',
      'accessibility_title': 'Accessibility & Display',
      'accessibility_subtitle': 'Customize text size, contrast, voice speed, and audio assistance.',
      'accessibility_preview_title': 'Live Preview',
      'accessibility_sample_disease': 'Tomato Early Blight',
      'accessibility_sample_advice': 'Spray Mancozeb (2g/L) and remove infected lower leaves.',
      'section_display_text': 'Display & Text',
      'text_size': 'Text Size',
      'text_size_normal': 'Normal (100%)',
      'text_size_medium': 'Medium (115%)',
      'text_size_large': 'Large (130%)',
      'text_size_xlarge': 'Extra Large (145%)',
      'high_contrast': 'High Contrast Mode',
      'high_contrast_desc': 'Enhance colors and borders for better visibility under outdoor sunlight.',
      'section_voice_audio': 'Voice & Audio (TTS)',
      'auto_read_diagnosis': 'Auto-Read Diagnosis',
      'auto_read_desc': 'Automatically play voice treatment guidance when diagnosis results appear.',
      'speech_rate': 'Voice Speed',
      'speech_rate_slow': 'Slower',
      'speech_rate_normal': 'Normal',
      'speech_rate_fast': 'Faster',
      'test_voice_btn': 'Test Voice',
      'test_voice_sample': 'Hello! This is how CropCare will read your crop treatment guidance.',
      'haptic_feedback': 'Haptic Feedback',
      'haptic_feedback_desc': 'Provide subtle vibrations on camera capture and diagnosis completion.',
      'reset_defaults': 'Reset to Defaults',
      'section_offline': 'Offline',
      'offline_title': 'Offline & Storage',
      'offline_subtitle': 'Sync status, auto-sync and local data storage',
      'sync_status_title': 'Cloud Sync Status',
      'sync_all_synced': 'All scans are backed up to cloud',
      'sync_pending_count': 'scans waiting to sync',
      'auto_sync_title': 'Auto-Sync',
      'auto_sync_desc': 'Automatically upload scans when internet connection is detected.',
      'delete_local_scans_title': 'Delete Local Scans',
      'delete_local_scans_desc': 'Free up storage by clearing all scan images and history from this device.',
      'delete_scans_confirm_title': 'Delete Local Scans?',
      'delete_scans_confirm_msg': 'This will delete all scans and diagnosis records stored on this device. This cannot be undone.',
      'unsynced_warning_title': 'Warning: Unsynced Scans',
      'unsynced_warning_msg': 'You have scans that have not yet been synced to your account. Deleting them now will permanently lose them.',
      'sync_first_btn': 'Sync First',
      'delete_anyway_btn': 'Delete Anyway',
      'all_scans_deleted': 'All local scans have been deleted.',
    },
    'si': {
      'app_title': 'CropCare',
      'splash_subtitle': 'ස්මාර්ට් බෝග සෞඛ්‍ය සහකාර',
      'onboarding_title_1': 'ගැටලුව හඳුනාගන්න',
      'onboarding_desc_1':
          'බෝග වල රෝග කල්තියා හඳුනා ගැනීමට ඡායාරූප ලබා ගන්න.',
      'onboarding_title_2': 'පැහැදිලි උපදෙස් ලබාගන්න',
      'onboarding_desc_2':
          'ඔබේම භාෂාවෙන් පැහැදිලි ප්‍රතිකාර උපදෙස් ලබා ගන්න.',
      'onboarding_title_3': 'විශේෂඥ උපදෙස් ලබාගන්න',
      'onboarding_desc_3':
          'AI අපැහැදිලි විට කෘෂිකාර්මික විශේෂඥයින්ගේ උපකාර ලබා ගන්න.',
      'skip': 'මඟහරින්න',
      'next': 'ඊළඟ',
      'get_started': 'ආරම්භ කරන්න',
      'select_language_title': 'ඔබේ භාෂාව තෝරන්න',
      'select_language_subtitle': 'CropCare සඳහා ඔබ කැමති භාෂාව තෝරන්න',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'තහවුරු කරන්න',
      'home_title': 'CropCare මුල් පිටුව',
      'home_welcome': 'CropCare වෙත සාදරයෙන් පිළිගනිමු!',
      'home_subtitle': 'බෝග රෝග හඳුනාගෙන නිවැරදි ප්‍රතිකාර උපදෙස් ලබාගන්න.',
      'change_language': 'භාෂාව වෙනස් කරන්න',
      'select_crop_title': 'බෝගය තෝරන්න',
      'select_crop_subtitle': 'ඔබට පරීක්ෂා කිරීමට අවශ්‍ය බෝගය තෝරන්න',
      'camera_permission_title': 'කැමරා අවසරය අවශ්‍යයි',
      'camera_permission_desc':
          'බෝග රෝග හඳුනාගැනීම සඳහා ඡායාරූප ගැනීමට CropCare හට කැමරා අවසරය අවශ්‍ය වේ.',
      'open_app_settings': 'යෙදුම් සැකසුම් විවෘත කරන්න',
      'grant_permission': 'අවසර දෙන්න',
      'capture_photo': 'ඡායාරූපයක් ගන්න',
      'review_photo_title': 'ඡායාරූපය පරීක්ෂා කරන්න',
      'retake': 'නැවත ගන්න',
      'use_photo': 'මෙම ඡායාරූපය භාවිතා කරන්න',
      'scan_result_title': 'පරීක්ෂණ විස්තර',
      'scan_id': 'ස්කෑන් අංකය',
      'crop': 'බෝගය',
      'image_path': 'ඡායාරූප මාර්ගය',
      'status': 'තත්ත්වය',
      'captured_at': 'ලබාගත් වේලාව',
      'settings_title': 'සැකසුම්',
      'section_language': 'භාෂාව',
      'section_accessibility': 'ප්‍රවේශ්‍යතාව',
      'section_notifications': 'දැනුම්දීම්',
      'section_offline_data': 'නොබැඳි දත්ත සහ සමමුහුර්තකරණය',
      'coming_soon': 'ළඟදීම බලාපොරොත්තු වන්න',
      'coming_soon_desc': 'මෙම විශේෂාංගය ළඟදීම එක් කෙරේ.',
      'start_scan': 'බෝගය පරීක්ෂා කරන්න',
      'diagnosis_result_title': 'රෝග විනිශ්චය ප්‍රතිඵලය',
      'treatment_guidance_title': 'ප්‍රතිකාර මාර්ගෝපදේශය',
      'treatment_summary': 'සාරාංශය',
      'treatment_what_to_do': 'කළ යුතු දේ',
      'treatment_what_to_avoid': 'නොකළ යුතු දේ',
      'recheck_after_days': 'නැවත පරීක්ෂා කරන්න',
      'days': 'දිනකින්',
      'treatment_source_llm': 'AI මඟින් ජනනය කළ උපදෙස්',
      'treatment_source_ai': 'AI',
      'treatment_source_offline': 'උපාංගය තුළ නොබැඳි',
      'offline_guideline_badge': 'උපාංගය තුළ නොබැඳි',
      'treatment_observations_label': 'ඔබේ නිරීක්ෂණ ඇතුළත් කරන්න (අවශ්‍ය නම්)',
      'treatment_observations_hint':
          'උදා: දින 3කට පෙර ආරම්භ විය, පහළ කොළ කහ පැහැ වේ...',
      'get_treatment_btn': 'AI උපදෙස් ලබාගන්න',
      'offline_connection_msg':
          'CropCare AI සේවාව හා සම්බන්ධ විය නොහැක. කරුණාකර ඔබගේ අන්තර්ජාල සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'retry_btn': 'නැවත උත්සාහ කරන්න',
      'healthy_crop_msg':
          'ඔබේ බෝගය නිරෝගී බව පෙනේ! සාමාන්‍ය වගා කටයුතු කරගෙන යන්න.',
      'ai_disclaimer':
          'AI ආධාරක අනාවැකියකි — රසායනික ප්‍රතිකාර යෙදීමට පෙර තහවුරු කරගන්න.',
      'scan_again': 'නැවත පරීක්ෂා කරන්න',
      'get_expert_help': 'WhatsApp මඟින් විශේෂඥ උපදෙස්',
      'disease_detected': 'හඳුනාගත් රෝගය',
      'confidence': 'විශ්වාසනීයත්වය',
      'severity': 'බරපතලකම',
      'fetching_treatment': 'AI කෘෂිකර්ම විශේෂඥයා විමසමින්...',
      'low_confidence_advisory':
          'අඩු විශ්වාසනීයත්වයක් සහිත AI ප්‍රතිඵලයකි (<80%). WhatsApp හරහා කෘෂිකාර්මික විශේෂඥයෙකුගෙන් උපදෙස් ලබා ගැනීමට අපි යෝජනා කරමු.',
      'escalation_title': 'විශේෂඥයෙකු වෙත යොමු කරන්න',
      'escalation_subtitle':
          'කොළයේ ඡායාරූපය සහ විස්තර WhatsApp හරහා විශේෂඥයෙකු වෙත යවන්න',
      'farmer_notes_label': 'විශේෂඥයා සඳහා ඔබේ නිරීක්ෂණ',
      'farmer_notes_hint':
          'උදා: වගා බිමේ ස්ථානය, රෝග ලක්ෂණ පැවති කාලය, යෙදූ පොහොර...',
      'share_whatsapp_btn': 'WhatsApp මඟින් විශේෂඥයාට යවන්න',
      'scan_history_title': 'පරීක්ෂණ ඉතිහාසය',
      'scan_history_empty':
          'තවම ස්කෑන් කර නැත. ඔබේ පළමු පරීක්ෂණය ආරම්භ කිරීමට ඉහත ඇති "බෝගය පරීක්ෂා කරන්න" තට්ටු කරන්න!',
      'filter_all': 'සියලු පරීක්ෂණ',
      'filter_low_conf': 'අඩු විශ්වාසනීයත්වය (<80%)',
      'filter_shared': 'විශේෂඥයන් හා බෙදාගත්',
      'filter_healthy': 'නිරෝගී බෝග',
      'filter_date_today': 'අද පරීක්ෂා කළ',
      'filter_date_week': 'මේ සතියේ පරීක්ෂා කළ',
      'filter_date_month': 'මේ මාසයේ පරීක්ෂා කළ',
      'filter_crop_tomato': 'බෝගය: තක්කාලි',
      'filter_crop_chili': 'බෝගය: මිරිස්',
      'filter_crop_paddy': 'බෝගය: වී / ගොයම්',
      'filter_crop_corn': 'බෝගය: ඉරිඟු',
      'filter_crop_potato': 'බෝගය: අර්තාපල්',
      'export_btn': 'බාගන්න',
      'scans_count': 'ස්කෑන්',
      'auth_title': 'ගිණුම සහ පිවිසුම',
      'sign_in': 'පුරනය වන්න',
      'create_account': 'ගිණුමක් සාදන්න',
      'email': 'විද්‍යුත් තැපෑල',
      'password': 'මුරපදය',
      'link_guest_account': 'මෙම දුරකථනයේ ස්කෑන් ඉතිහාසය ඔබගේ ගිණුමට සම්බන්ධ කරන්න',
      'guest_badge': 'ආගන්තුක මාදිලිය',
      'link_account_btn': 'ගිණුම සම්බන්ධ කරන්න',
      'signed_in_as': 'පිවිස ඇත්තේ',
      'sign_out': 'ඉවත් වන්න',
      'email_invalid': 'වලංගු විද්‍යුත් තැපැල් ලිපිනයක් ඇතුළත් කරන්න',
      'password_short': 'මුරපදය අවම වශයෙන් අක්ෂර 6ක් විය යුතුය',
      'account_section': 'ගිණුම',
      'account_guest_desc': 'ඔබ ආගන්තුකයෙකු ලෙස භාවිත කරයි. ස්කෑන් සුරැකීමට ගිණුමක් සාදන්න.',
      'read_aloud': 'හඬින් අසන්න',
      'stop_reading': 'හඬ නතර කරන්න',
      'playing_audio': 'හඬ ධාවනය වේ...',
      'sync_now': 'දැන් සමමුහුර්ත කරන්න',
      'sync_pending': 'සමමුහුර්ත කිරීමට ඇත',
      'sync_in_progress': 'දත්ත වලාකුළට සමමුහුර්ත වේ...',
      'sync_success': 'සියලු දත්ත වලාකුළට සමමුහුර්ත විය',
      'sync_offline_ready': 'නොබැඳිව සූදානම්',
      'auth_method_email': 'විද්‍යුත් තැපෑල',
      'auth_method_phone': 'දුරකථනය',
      'phone_number': 'දුරකථන අංකය',
      'phone_invalid': 'වලංගු දුරකථන අංකයක් ඇතුළත් කරන්න (උදා: +94771234567)',
      'otp_entry_title': 'තහවුරු කිරීමේ කේතය ඇතුළත් කරන්න',
      'otp_code_label': 'ඉලක්කම් 6 කේතය',
      'otp_submit': 'තහවුරු කර ඉදිරියට යන්න',
      'otp_resend': 'නැවත කේතය එවන්න',
      'otp_resend_in': 'තත්පර {n} කින් නැවත එවන්න',
      'otp_expired': 'තහවුරු කිරීමේ කේතය කල් ඉකුත් වී ඇත. කරුණාකර අලුත් කේතයක් ඉල්ලන්න.',
      'otp_wrong_code': 'වැරදි තහවුරු කිරීමේ කේතයකි. කරුණාකර පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
      'forgot_password': 'මුරපදය අමතකද?',
      'forgot_password_title': 'මුරපදය නැවත සකසන්න',
      'forgot_password_subtitle':
          'මුරපදය නැවත සැකසීමේ උපදෙස් ලබා ගැනීමට ඔබේ ලියාපදිංචි විද්‍යුත් තැපෑල ඇතුළත් කරන්න.',
      'send_reset_link': 'උපදෙස් එවන්න',
      'reset_link_sent_title': 'විද්‍යුත් තැපෑල යවන ලදී',
      'reset_link_sent_desc':
          'මෙම ලිපිනය සඳහා ගිණුමක් ඇත්නම්, මුරපදය නැවත සැකසීමේ උපදෙස් යවා ඇත. කරුණාකර ඔබගේ විද්‍යුත් තැපැල් පරීක්ෂා කරන්න.',
      'back_to_sign_in': 'ආපසු පිවිසුමට',
      'consent_agreement_prefix': 'ගිණුමක් සෑදීමෙන්, ඔබ අපගේ',
      'terms_of_service': 'සේවා කොන්දේසි',
      'privacy_policy': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
      'and_connector': 'සහ',
      'section_help_faq': 'උදව් සහ නිතර අසන ප්‍රශ්න',
      'section_terms_privacy': 'කොන්දේසි සහ පෞද්ගලිකත්වය',
      'faq_title': 'නිතර අසන ප්‍රශ්න',
      'faq_category_scanning': 'ස්කෑන් කිරීම සහ රෝග හඳුනාගැනීම',
      'faq_q1': 'බෝග රෝග හඳුනාගැනීම ක්‍රියා කරන්නේ කෙසේද?',
      'faq_a1':
          'CropCare ඔබගේ දුරකථනයේ ඇති AI තාක්ෂණය මඟින් කොළ ඡායාරූප විශ්ලේෂණය කරයි. අන්තර්ජාලය ඇති විට සවිස්තරාත්මක ප්‍රතිකාර උපදෙස් ලබාදේ.',
      'faq_q2': 'අන්තර්ජාලය නොමැතිව CropCare භාවිත කළ හැකිද?',
      'faq_a2':
          'ඔව්! රෝග හඳුනාගැනීම සහ නොබැඳි මාර්ගෝපදේශ අන්තර්ජාලය නොමැතිව ක්‍රියා කරයි. ස්කෑන් ඔබගේ දුරකථනයේ සුරැකේ.',
      'faq_q3': 'විශ්වාසනීයත්වය අඩු නම් කුමක් කළ යුතුද?',
      'faq_a3':
          'විශ්වාසනීයත්වය 80% ට අඩු වූ විට, WhatsApp හරහා ඡායාරූපය සහ සටහන් සමඟ කෘෂිකාර්මික විශේෂඥයෙකු වෙත යොමු කළ හැක.',
      'faq_category_account_sync': 'ගිණුම සහ සමමුහුර්තකරණය',
      'faq_q4': 'මම ගිණුමක් සෑදිය යුතුද?',
      'faq_a4':
          'නැත. ආගන්තුකයෙකු ලෙස භාවිත කළ හැක. ගිණුමක් සෑදීමෙන් ඔබගේ ස්කෑන් වෙනත් දුරකථන සමඟ සමමුහුර්ත කරගත හැක.',
      'faq_q5': 'වලාකුළු සමමුහුර්තකරණය ක්‍රියා කරන්නේ කෙසේද?',
      'faq_a5':
          'අන්තර්ජාලය ඇති විට Settings වෙත ගොස් "Sync Now" තට්ටු කරන්න, නැතහොත් පසුබිමෙන් ස්වයංක්‍රීයව සමමුහුර්ත වේ.',
      'terms_privacy_title': 'කොන්දේසි සහ පෞද්ගලිකත්වය',
      'terms_tab': 'සේවා කොන්දේසි',
      'privacy_tab': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
      'terms_content_title': 'CropCare සේවා කොන්දේසි',
      'terms_content_body':
          '1. අරමුණ\nCropCare යනු ගොවීන්ට රෝග හඳුනාගැනීමට සහාය වන AI මෙවලමකි. එය වෘත්තීය කෘෂි උපදෙස් වෙනුවට සම්පූර්ණ ආදේශකයක් නොවේ.\n\n2. AI නිරවද්‍යතාව\nරසායනික ප්‍රතිකාර යෙදීමට පෙර ප්‍රාදේශීය කෘෂිකර්ම නිලධාරීන්ගෙන් තහවුරු කරගන්න.\n\n3. පරිශීලක වගකීම\nඔබ අදාළ බෝග ඡායාරූප පමණක් ලබා ගැනීමට එකඟ වේ.',
      'privacy_content_title': 'CropCare පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
      'privacy_content_body':
          '1. දත්ත රැස් කිරීම\nඅපි ඔබ ලබාගන්නා බෝග ඡායාරූප, රෝග ඉතිහාසය සහ ගිණුම් විස්තර පමණක් ලබා ගනිමු.\n\n2. දේශීය දත්ත ගබඩා කිරීම\nඔබේ ස්කෑන් ඉතිහාසය ඔබේ දුරකථනයේ ආරක්ෂිතව සුරැකේ.\n\n3. තෙවන පාර්ශවයන්ට ලබා නොදීම\nඅපි කිසිවිටෙකත් ඔබගේ පෞද්ගලික දත්ත තෙවන පාර්ශවයන්ට විකුණන්නේ නැත.',
      'pick_from_gallery': 'ගැලරියෙන් තෝරන්න',
      'gallery_button_label': 'ගැලරිය',
      'export_data_title': 'ස්කෑන් ඉතිහාසය පිටපත් කරන්න',
      'export_data_desc':
          'ඔබේ සියලුම ස්කෑන් වල CSV පිටපතක් ලබාගන්න හෝ බෙදාගන්න.',
      'export_data_empty': 'පිටපත් කිරීමට ස්කෑන් කිසිවක් නැත.',
      'export_data_success': 'ස්කෑන් ඉතිහාසය සාර්ථකව පිටපත් කෙරිණි.',
      'export_data_btn': 'පිටපත් කරන්න',
      'section_profile': 'පැතිකඩ සහ ගිණුම',
      'section_preferences': 'මනාපයන්',
      'section_data_storage': 'දත්ත සහ ආචයනය',
      'section_support_legal': 'සහාය සහ නීතිමය',
      'app_version': 'යෙදුම් අනුවාදය',
      'profile_title': 'පරිශීලක පැතිකඩ',
      'profile_account_info': 'ගිණුම් තොරතුරු',
      'profile_account_type': 'ගිණුම් වර්ගය',
      'profile_registered_user': 'ලියාපදිංචි ගිණුම',
      'profile_user_id': 'පරිශීලක හැඳුනුම්පත',
      'change_email': 'විද්‍යුත් තැපෑල වෙනස් කරන්න',
      'enter_new_email': 'නව විද්‍යුත් තැපැල් ලිපිනය ඇතුළත් කරන්න',
      'change_phone': 'දුරකථන අංකය වෙනස් කරන්න',
      'enter_new_phone': 'නව දුරකථන අංකය ඇතුළත් කරන්න (උදා: +94771234567)',
      'verify_new_phone': 'දුරකථන අංකය තහවුරු කරන්න',
      'send_code': 'කේතය එවන්න',
      'save_changes': 'සුරකින්න',
      'delete_account': 'ගිණුම මකා දමන්න',
      'delete_account_desc':
          'ඔබගේ ගිණුම සහ ක්ලවුඩ් දත්ත ස්ථිරවම මකා දමන්න.',
      'delete_account_confirm_title': 'ගිණුම මකා දැමීම තහවුරු කරන්නද?',
      'delete_account_confirm_desc':
          'මෙම ක්‍රියාව ආපසු හැරවිය නොහැක. ඔබගේ ගිණුම සහ ක්ලවුඩ් දත්ත ස්ථිරවම ඉවත් කරනු ලැබේ.',
      'delete_account_action': 'ඔව්, මගේ ගිණුම මකන්න',
      'delete_account_success': 'ඔබගේ ගිණුම මකා දමන ලදී.',
      'cancel': 'අවලංගු කරන්න',
      'send_feedback': 'ප්‍රතිපෝෂණ එවන්න',
      'feedback_title': 'ප්‍රතිපෝෂණ සහ යෝජනා',
      'feedback_subtitle':
          'CropCare වැඩිදියුණු කිරීමට අපට සහාය වන්න. ඔබේ අදහස් හෝ ගැටලු බෙදාගන්න.',
      'feedback_category': 'වර්ගය',
      'category_general': 'සාමාන්‍ය ප්‍රතිපෝෂණය',
      'category_bug': 'ගැටලුවක් / දෝෂයක් වාර්තා කරන්න',
      'category_suggestion': 'නව විශේෂාංග යෝජනාවක්',
      'feedback_hint': 'ඔබේ ප්‍රතිපෝෂණය මෙහි ලියන්න...',
      'feedback_submit': 'ප්‍රතිපෝෂණය යවන්න',
      'feedback_success': 'ස්තූතියි! ඔබේ ප්‍රතිපෝෂණය ලැබිණි.',
      'feedback_empty_error': 'කරුණාකර යැවීමට පෙර පණිවිඩයක් ඇතුළත් කරන්න.',
      'cancel_scan': 'ස්කෑන් කිරීම අවලංගු කරන්න',
      'copy_summary_btn': 'සාරාංශය පිටපත් කරන්න',
      'summary_copied': 'රෝග විනිශ්චය සාරාංශය පසුරුපුවරුවට පිටපත් කෙරිණි.',
      'share_other_apps': 'වෙනත් යෙදුම් මගින් බෙදාගන්න',
      'view_profile': 'පැතිකඩ බලන්න',
      'back_to_home': 'මුල් පිටුවට',
      'low_confidence_badge': 'අඩු විශ්වාසනීයත්වයක්',
      'add_photo_title': 'නව ස්කෑන් පරීක්ෂාවක්',
      'add_photo_subtitle': 'AI රෝග විනිශ්චය සඳහා ශාකයේ ඡායාරූපයක් ගන්න හෝ ගැලරියෙන් තෝරන්න.',
      'take_photo_btn': 'ඡායාරූපයක් ගන්න',
      'take_photo_desc': 'කැමරාව මඟින් පත්‍රය ස්කෑන් කරන්න',
      'choose_gallery_btn': 'ගැලරියෙන් තෝරන්න',
      'choose_gallery_desc': 'ඡායාරූප පුස්තකාලයෙන් උඩුගත කරන්න',
      'supported_crops_label': 'සහාය දක්වන බෝග',
      'supported_crops_desc': 'AI මාදිලිය පහත සඳහන් බෝග හඳුනා ගැනීමට පුහුණු කර ඇත:',
      'gallery_permission_denied_title': 'ගැලරි අවසරය අවශ්‍යයි',
      'gallery_permission_denied_desc': 'ඡායාරූප තෝරා ගැනීමට කරුණාකර සැකසුම් තුළ ගැලරි ප්‍රවේශය ලබා දෙන්න.',
      'open_settings': 'සැකසුම් විවෘත කරන්න',
      'unknown_crop': 'නොදන්නා බෝගය',
      'accessibility_title': 'ප්‍රවේශ්‍යතාව සහ සංදර්ශකය',
      'accessibility_subtitle': 'අකුරු ප්‍රමාණය, වෙනස, හඬ වේගය සහ ශ්‍රව්‍ය සහාය සකසන්න.',
      'accessibility_preview_title': 'සජීවී පෙරදසුන',
      'accessibility_sample_disease': 'තක්කාලි අංගමාරය',
      'accessibility_sample_advice': 'මැන්කොසෙබ් (ලීටරයකට ග්‍රෑම් 2) ඉසින්න සහ ආසාදිත පහළ කොළ ඉවත් කරන්න.',
      'section_display_text': 'සංදර්ශකය සහ අකුරු',
      'text_size': 'අකුරු ප්‍රමාණය',
      'text_size_normal': 'සාමාන්‍ය (100%)',
      'text_size_medium': 'මධ්‍යම (115%)',
      'text_size_large': 'විශාල (130%)',
      'text_size_xlarge': 'ඉතා විශාල (145%)',
      'high_contrast': 'ඉහළ වෙනස සහිත මාදිලිය (High Contrast)',
      'high_contrast_desc': 'එළිමහන් හිරු එළියේදී පැහැදිලිව පෙනෙන පරිදි වර්ණ සහ මායිම් වැඩි දියුණු කරන්න.',
      'section_voice_audio': 'හඬ සහ ශ්‍රව්‍ය (TTS)',
      'auto_read_diagnosis': 'ස්වයංක්‍රීයව ශ්‍රව්‍ය කියවීම',
      'auto_read_desc': 'රෝග විනිශ්චය ලැබුණු වහාම ප්‍රතිකාර උපදෙස් ස්වයංක්‍රීයව හඬින් කියවන්න.',
      'speech_rate': 'හඬ වේගය',
      'speech_rate_slow': 'සෙමින්',
      'speech_rate_normal': 'සාමාන්‍ය',
      'speech_rate_fast': 'වේගවත්',
      'test_voice_btn': 'හඬ පරීක්ෂා කරන්න',
      'test_voice_sample': 'ආයුබෝවන්! CropCare ඔබේ බෝග ප්‍රතිකාර උපදෙස් කියවන්නේ මෙසේය.',
      'haptic_feedback': 'ස්පර්ශ කම්පනය (Vibration)',
      'haptic_feedback_desc': 'ඡායාරූප ගැනීමේදී සහ රෝග විනිශ්චය අවසානයේදී කම්පන ප්‍රතිචාර ලබාදෙන්න.',
      'reset_defaults': 'යථා තත්වයට පත් කරන්න',
      'section_offline': 'නොබැඳි මාදිලිය (Offline)',
      'offline_title': 'නොබැඳි සහ දත්ත ගබඩාව',
      'offline_subtitle': 'සමමුහුර්ත තත්වය, ස්වයංක්‍රීය සමමුහුර්තකරණය සහ දේශීය දත්ත',
      'sync_status_title': 'Cloud සමමුහුර්තකරණ තත්වය',
      'sync_all_synced': 'සියලුම ස්කෑන් Cloud වෙත සුරක්ෂිත කර ඇත',
      'sync_pending_count': 'ක් Cloud වෙත යැවීමට ඉතිරිව ඇත',
      'auto_sync_title': 'ස්වයංක්‍රීය සමමුහුර්තකරණය',
      'auto_sync_desc': 'අන්තර්ජාල සම්බන්ධතාවය ලැබුණු වහාම ස්කෑන් ස්වයංක්‍රීයව Cloud වෙත උඩුගත කරන්න.',
      'delete_local_scans_title': 'දේශීය ස්කෑන් ඉවත් කරන්න',
      'delete_local_scans_desc': 'මෙම උපාංගයේ ඇති සියලුම ස්කෑන් ඡායාරූප සහ ඉතිහාසය මකා දමා මතකය නිදහස් කරන්න.',
      'delete_scans_confirm_title': 'දේශීය ස්කෑන් මකා දැමිය යුතුද?',
      'delete_scans_confirm_msg': 'මෙය මෙම උපාංගයේ සුරකින ලද සියලුම ස්කෑන් සහ රෝග විනිශ්චය වාර්තා මකා දමනු ඇත. මෙය නැවත ලබා ගත නොහැක.',
      'unsynced_warning_title': 'අවවාදයයි: සමමුහුර්ත නොකළ ස්කෑන් පවතී',
      'unsynced_warning_msg': 'ඔබගේ ගිණුමට තවමත් සමමුහුර්ත කර නොමැති ස්කෑන් කිහිපයක් තිබේ. දැන් ඒවා මකා දැමුවහොත් ඒවා සදහටම අහිමි වනු ඇත.',
      'sync_first_btn': 'පළමුව සමමුහුර්ත කරන්න',
      'delete_anyway_btn': 'කෙසේ හෝ මකන්න',
      'all_scans_deleted': 'සියලුම දේශීය ස්කෑන් මකා දමන ලදී.',
    },
    'ta': {
      'app_title': 'CropCare',
      'splash_subtitle': 'ஸ்மார்ட் பயிர் சுகாதார உதவியாளர்',
      'onboarding_title_1': 'பிரச்சனையைக் கண்டறியவும்',
      'onboarding_desc_1':
          'பயிர் நோய்களை முன்கூட்டியே கண்டறிய புகைப்படங்களை எடுக்கவும்.',
      'onboarding_title_2': 'தெளிவான வழிகாட்டுதலைப் பெறுக',
      'onboarding_desc_2':
          'உங்கள் மொழியில் தெளிவான சிகிச்சை வழிமுறைகளைப் பெறுங்கள்.',
      'onboarding_title_3': 'நிபுணர் உதவியைப் பெறுங்கள்',
      'onboarding_desc_3':
          'AI பலவீனமாக இருக்கும் போது விவசாய நிபுணர்களின் உதவியைப் பெறுங்கள்.',
      'skip': 'தவிர்',
      'next': 'அடுத்து',
      'get_started': 'தொடங்கவும்',
      'select_language_title': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_language_subtitle':
          'CropCare க்கான உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'உறுதிப்படுத்து',
      'home_title': 'CropCare முகப்பு',
      'home_welcome': 'CropCare க்கு நல்வரவு!',
      'home_subtitle': 'பயிர் நோய்களைக் கண்டறிந்து உடனடி சிகிச்சை ஆலோசனைகளைப் பெறுங்கள்.',
      'change_language': 'மொழியை மாற்றவும்',
      'select_crop_title': 'பயிரைத் தேர்ந்தெடுக்கவும்',
      'select_crop_subtitle':
          'நீங்கள் ஸ்கேன் செய்ய விரும்பும் பயிரைத் தேர்ந்தெடுக்கவும்',
      'camera_permission_title': 'கேமரா அனுமதி தேவை',
      'camera_permission_desc':
          'பயிர் நோய் கண்டறிதலுக்கு புகைப்படங்களை எடுக்க CropCare க்கு கேமரா அனுமதி தேவை.',
      'open_app_settings': 'பயன்பாட்டு அமைப்புகளைத் திறக்கவும்',
      'grant_permission': 'அனுமதி அளிக்கவும்',
      'capture_photo': 'புகைப்படம் எடுக்கவும்',
      'review_photo_title': 'புகைப்படத்தை மதிப்பாய்வு செய்யவும்',
      'retake': 'மீண்டும் எடுக்கவும்',
      'use_photo': 'புகைப்படத்தைப் பயன்படுத்தவும்',
      'scan_result_title': 'ஸ்கேன் விவரங்கள்',
      'scan_id': 'ஸ்கேன் ஐடி',
      'crop': 'பயிர்',
      'image_path': 'படப் பாதை',
      'status': 'நிலை',
      'captured_at': 'எடுக்கப்பட்ட நேரம்',
      'settings_title': 'அமைப்புகள்',
      'section_language': 'மொழி',
      'section_accessibility': 'அணுகல்தன்மை',
      'section_notifications': 'அறிவிப்புகள்',
      'section_offline_data': 'ஆஃப்லைன் தரவு & ஒத்திசைவு',
      'coming_soon': 'விரைவில்',
      'coming_soon_desc': 'இந்த அம்சம் விரைவில் கிடைக்கும்.',
      'start_scan': 'பயிரைச் சோதிக்கவும்',
      'diagnosis_result_title': 'நோய் கண்டறிதல் முடிவு',
      'treatment_guidance_title': 'சிகிச்சை வழிகாட்டுதல்',
      'treatment_summary': 'சுருக்கம்',
      'treatment_what_to_do': 'செய்ய வேண்டியவை',
      'treatment_what_to_avoid': 'தவிர்க்க வேண்டியவை',
      'recheck_after_days': 'மீண்டும் பரிசோதிக்கவும்',
      'days': 'நாட்களில்',
      'treatment_source_llm': 'AI உருவாக்கிய ஆலோசனை',
      'treatment_source_ai': 'AI',
      'treatment_source_offline': 'சாதன ஆஃப்லைன்',
      'offline_guideline_badge': 'சாதன ஆஃப்லைன்',
      'treatment_observations_label': 'உங்கள் அவதானிப்புகளைச் சேர்க்கவும் (விருப்பத்திற்குரியது)',
      'treatment_observations_hint':
          'எ.கா. 3 நாட்களுக்கு முன் தொடங்கியது, கீழ் இலைகள் மஞ்சள் நிறமாகிறது...',
      'get_treatment_btn': 'AI பரிந்துரையைப் பெறுங்கள்',
      'offline_connection_msg':
          'CropCare AI உடன் இணைக்க முடியவில்லை. உங்கள் இணையம் அல்லது Wi-Fi இணைப்பைச் சரிபார்க்கவும்.',
      'retry_btn': 'மீண்டும் முயற்சிக்கவும்',
      'healthy_crop_msg':
          'உங்கள் பயிர் ஆரோக்கியமாகத் தெரிகிறது! வழக்கமான விவசாய முறைகளைத் தொடரவும்.',
      'ai_disclaimer':
          'AI உதவி முன்னறிவிப்பு — இரசாயனங்களைப் பயன்படுத்துவதற்கு முன் சரிபார்க்கவும்.',
      'scan_again': 'மீண்டும் ஸ்கேன் செய்யவும்',
      'get_expert_help': 'நிபுணருடன் WhatsApp இல் பகிரவும்',
      'disease_detected': 'கண்டறியப்பட்ட நோய்',
      'confidence': 'நம்பகத்தன்மை',
      'severity': 'தீவிரம்',
      'fetching_treatment': 'AI விவசாய நிபுணரிடம் ஆலோசனை பெறுகிறது...',
      'low_confidence_advisory':
          'குறைந்த நம்பகத்தன்மை கொண்ட AI முடிவு (<80%). வாட்ஸ்அப் மூலம் விவசாய நிபுணரிடம் ஆலோசனை பெற பரிந்துரைக்கிறோம்.',
      'escalation_title': 'நிபுணரிடம் பரிந்துரைக்கவும்',
      'escalation_subtitle':
          'இலை புகைப்படம் மற்றும் நோய் விவரங்களை வாட்ஸ்அப்பில் பகிரவும்',
      'farmer_notes_label': 'நிபுணருக்கான உங்கள் அவதானிப்புகள்',
      'farmer_notes_hint':
          'எ.கா. வயல் இருப்பிடம், அறிகுறிகள் நீடித்த காலம், பயன்படுத்திய உரம்...',
      'share_whatsapp_btn': 'WhatsApp மூலம் நிபுணருடன் பகிரவும்',
      'scan_history_title': 'முந்தைய ஸ்கேன்கள்',
      'scan_history_empty':
          'இதுவரை ஸ்கேன்கள் இல்லை. உங்கள் முதல் பரிசோதனையைத் தொடங்க மேலே உள்ள "பயிரைச் சோதிக்கவும்" என்பதைத் தட்டவும்!',
      'filter_all': 'அனைத்து ஸ்கேன்கள்',
      'filter_low_conf': 'குறைந்த நம்பகத்தன்மை (<80%)',
      'filter_shared': 'பகிரப்பட்டவை',
      'filter_healthy': 'ஆரோக்கியமான பயிர்கள்',
      'filter_date_today': 'இன்று பரிசோதித்தவை',
      'filter_date_week': 'இந்த வாரம் பரிசோதித்தவை',
      'filter_date_month': 'இந்த மாதம் பரிசோதித்தவை',
      'filter_crop_tomato': 'பயிர்: தக்காளி',
      'filter_crop_chili': 'பயிர்: மிளகாய்',
      'filter_crop_paddy': 'பயிர்: நெல்',
      'filter_crop_corn': 'பயிர்: சோளம்',
      'filter_crop_potato': 'பயிர்: உருளைக்கிழங்கு',
      'export_btn': 'ஏற்றுமதி',
      'scans_count': 'ஸ்கேன்கள்',
      'auth_title': 'கணக்கு மற்றும் உள்நுழைவு',
      'sign_in': 'உள்நுழைக',
      'create_account': 'கணக்கை உருவாக்கவும்',
      'email': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'link_guest_account': 'இந்த சாதனத்தின் ஸ்கேன் வரலாற்றை உங்கள் கணக்குடன் இணைக்கவும்',
      'guest_badge': 'விருந்தினர் பயன்முறை',
      'link_account_btn': 'கணக்கை இணைக்கவும்',
      'signed_in_as': 'உள்நுழைந்துள்ளீர்கள்',
      'sign_out': 'வெளியேறு',
      'email_invalid': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'password_short': 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்களாக இருக்க வேண்டும்',
      'account_section': 'கணக்கு',
      'account_guest_desc': 'நீங்கள் விருந்தினராகப் பயன்படுத்துகிறீர்கள். ஸ்கேன்களைச் சேமிக்க கணக்கை உருவாக்கவும்.',
      'read_aloud': 'கேட்கவும்',
      'stop_reading': 'நிறுத்தவும்',
      'playing_audio': 'ஒலி ஒலிக்கிறது...',
      'sync_now': 'இப்போது ஒத்திசைக்கவும்',
      'sync_pending': 'ஒத்திசைக்க நிலுவையில் உள்ளது',
      'sync_in_progress': 'கிளவுட்டுடன் ஒத்திசைக்கப்படுகிறது...',
      'sync_success': 'அனைத்து தரவுகளும் ஒத்திசைக்கப்பட்டன',
      'sync_offline_ready': 'ஆஃப்லைனில் தயார்',
      'auth_method_email': 'மின்னஞ்சல்',
      'auth_method_phone': 'தொலைபேசி',
      'phone_number': 'தொலைபேசி எண்',
      'phone_invalid': 'செல்லுபடியாகும் தொலைபேசி எண்ணை உள்ளிடவும் (எ.கா: +94771234567)',
      'otp_entry_title': 'சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
      'otp_code_label': '6-இலக்க குறியீடு',
      'otp_submit': 'சரிபார்த்து தொடரவும்',
      'otp_resend': 'குறியீட்டை மீண்டும் அனுப்பவும்',
      'otp_resend_in': '{n} வினாடிகளில் மீண்டும் அனுப்பவும்',
      'otp_expired': 'சரிபார்ப்புக் குறியீடு காலாவதியானது. புதிய குறியீட்டைக் கோரவும்.',
      'otp_wrong_code': 'தவறான சரிபார்ப்புக் குறியீடு. சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'forgot_password_title': 'கடவுச்சொல்லை மீட்டமைக்கவும்',
      'forgot_password_subtitle':
          'கடவுச்சொல் மீட்டமைப்பு வழிமுறைகளைப் பெற உங்கள் பதிவுசெய்த மின்னஞ்சலை உள்ளிடவும்.',
      'send_reset_link': 'வழிமுறைகளை அனுப்பவும்',
      'reset_link_sent_title': 'மின்னஞ்சல் அனுப்பப்பட்டது',
      'reset_link_sent_desc':
          'இந்த மின்னஞ்சலில் கணக்கு இருந்தால், மீட்டமைப்பு வழிமுறைகள் அனுப்பப்பட்டுள்ளன. உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்.',
      'back_to_sign_in': 'உள்நுழைவுக்குத் திரும்புக',
      'consent_agreement_prefix': 'கணக்கை உருவாக்குவதன் மூலம், நீங்கள் எங்கள்',
      'terms_of_service': 'சேவை விதிமுறைகள்',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'and_connector': 'மற்றும்',
      'section_help_faq': 'உதவி & அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'section_terms_privacy': 'விதிமுறைகள் & தனியுரிமை',
      'faq_title': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'faq_category_scanning': 'ஸ்கேனிங் மற்றும் நோய் கண்டறிதல்',
      'faq_q1': 'பயிர் நோய் கண்டறிதல் எவ்வாறு செயல்படுகிறது?',
      'faq_a1':
          'CropCare உங்கள் தொலைபேசியிலேயே AI மாதிரிகளைப் பயன்படுத்தி இலை புகைப்படங்களை பகுப்பாய்வு செய்கிறது. இணையம் இருக்கும் போது விரிவான ஆலோசனைகளை வழங்குகிறது.',
      'faq_q2': 'இணையம் இல்லாமல் CropCare ஐப் பயன்படுத்த முடியுமா?',
      'faq_a2':
          'ஆம்! நோய் கண்டறிதல் மற்றும் ஆஃப்லைன் வழிகாட்டுதல்கள் இணையம் இல்லாமல் செயல்படும். ஸ்கேன்கள் சாதனத்தில் சேமிக்கப்படும்.',
      'faq_q3': 'நம்பகத்தன்மை குறைவாக இருந்தால் என்ன செய்வது?',
      'faq_a3':
          'நம்பகத்தன்மை 80% க்கும் குறைவாக இருக்கும்போது, WhatsApp மூலம் விவசாய நிபுணரிடம் ஆலோசனை பெறலாம்.',
      'faq_category_account_sync': 'கணக்கு & கிளவுட் ஒத்திசைவு',
      'faq_q4': 'நான் கணக்கை உருவாக்க வேண்டுமா?',
      'faq_a4':
          'இல்லை. விருந்தினர் பயன்முறையில் பயன்படுத்தலாம். கணக்கை உருவாக்குவது பல சாதனங்களில் தரவை ஒத்திசைக்க உதவும்.',
      'faq_q5': 'கிளவுட் ஒத்திசைவு எவ்வாறு செயல்படுகிறது?',
      'faq_a5':
          'இணையம் இருக்கும்போது Settings இல் "Sync Now" என்பதைத் தட்டவும் அல்லது தானாகவே பின்னணியில் ஒத்திசைக்கப்படும்.',
      'terms_privacy_title': 'விதிமுறைகள் & தனியுரிமைக் கொள்கை',
      'terms_tab': 'சேவை விதிமுறைகள்',
      'privacy_tab': 'தனியுரிமைக் கொள்கை',
      'terms_content_title': 'CropCare சேவை விதிமுறைகள்',
      'terms_content_body':
          '1. நோக்கம்\nCropCare என்பது விவசாயிகளுக்கு ஆரம்பகால நோய் கண்டறிதலில் உதவும் AI கருவியாகும். இது தொழில்முறை விவசாய ஆலோசனையை மாற்றாது.\n\n2. AI துல்லியம்\nஇரசாயன சிகிச்சைகளைப் பயன்படுத்துவதற்கு முன் உள்ளூர் விவசாய அதிகாரிகளுடன் சரிபார்க்கவும்.\n\n3. பயனர் நடத்தை\nதொடர்புடைய இலை புகைப்படங்களை மட்டுமே எடுக்க ஒப்புக்கொள்கிறீர்கள்.',
      'privacy_content_title': 'CropCare தனியுரிமைக் கொள்கை',
      'privacy_content_body':
          '1. தரவு சேகரிப்பு\nநீங்கள் எடுக்கும் பயிர் புகைப்படங்கள், நோய் வரலாறு மற்றும் கணக்கு விவரங்களை மட்டுமே சேகரிக்கிறோம்.\n\n2. சாதனத்திலேயே சேமிப்பு\nஉங்கள் ஸ்கேன் வரலாறு உங்கள் தொலைபேசியிலேயே பாதுகாப்பாக சேமிக்கப்படும்.\n\n3. மூன்றாம் தரப்பினருக்கு வழங்கப்படாது\nஉங்கள் தனிப்பட்ட தகவல்களை நாங்கள் ஒருபோதும் விற்பனை செய்வதில்லை.',
      'pick_from_gallery': 'கேலரியில் இருந்து தேர்ந்தெடுக்கவும்',
      'gallery_button_label': 'கேலரி',
      'export_data_title': 'ஸ்கேன் வரலாற்றை ஏற்றுமதி செய்க',
      'export_data_desc':
          'உங்கள் உள்ளூர் ஸ்கேன்களின் CSV நகலைப் பதிவிறக்கவும் அல்லது பகிரவும்.',
      'export_data_empty': 'ஏற்றுமதி செய்ய ஸ்கேன்கள் எதுவும் இல்லை.',
      'export_data_success': 'ஸ்கேன் வரலாறு வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது.',
      'export_data_btn': 'ஏற்றுமதி',
      'section_profile': 'சுயவிவரம் & கணக்கு',
      'section_preferences': 'விருப்பத்தேர்வுகள்',
      'section_data_storage': 'தரவு & சேமிப்பகம்',
      'section_support_legal': 'ஆதரவு & சட்டபூர்வமான',
      'app_version': 'பயன்பாட்டு பதிப்பு',
      'profile_title': 'பயனர் சுயவிவரம்',
      'profile_account_info': 'கணக்கு தகவல்',
      'profile_account_type': 'கணக்கு வகை',
      'profile_registered_user': 'பதிவுசெய்யப்பட்ட கணக்கு',
      'profile_user_id': 'பயனர் ஐடி',
      'change_email': 'மின்னஞ்சலை மாற்றவும்',
      'enter_new_email': 'புதிய மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'change_phone': 'தொலைபேசி எண்ணை மாற்றவும்',
      'enter_new_phone': 'புதிய தொலைபேசி எண்ணை உள்ளிடவும் (எ.கா. +94771234567)',
      'verify_new_phone': 'தொலைபேசி எண்ணைச் சரிபார்க்கவும்',
      'send_code': 'குறியீட்டை அனுப்பவும்',
      'save_changes': 'சேமிக்கவும்',
      'delete_account': 'கணக்கை நீக்குக',
      'delete_account_desc':
          'உங்கள் கணக்கு மற்றும் கிளவுட் ஒத்திசைவு தரவை நிரந்தரமாக நீக்கவும்.',
      'delete_account_confirm_title': 'கணக்கை நீக்க வேண்டுமா?',
      'delete_account_confirm_desc':
          'இந்த செயலை செயல்தவிர்க்க முடியாது. உங்கள் கணக்கு மற்றும் ஒத்திசைக்கப்பட்ட தரவு நிரந்தரமாக அகற்றப்படும்.',
      'delete_account_action': 'ஆம், எனது கணக்கை நீக்குக',
      'delete_account_success': 'உங்கள் கணக்கு நீக்கப்பட்டது.',
      'cancel': 'ரத்துசெய்',
      'send_feedback': 'கருத்து அனுப்பவும்',
      'feedback_title': 'கருத்து மற்றும் பரிந்துரைகள்',
      'feedback_subtitle':
          'CropCare ஐ மேம்படுத்த எங்களுக்கு உதவுங்கள். உங்கள் எண்ணங்கள் அல்லது சிக்கல்களைப் பகிரவும்.',
      'feedback_category': 'வகை',
      'category_general': 'பொதுவான கருத்து',
      'category_bug': 'சிக்கல் / பிழையைப் புகாரளிக்கவும்',
      'category_suggestion': 'அம்ச பரிந்துரை',
      'feedback_hint': 'உங்கள் கருத்தை இங்கே தட்டச்சு செய்யவும்...',
      'feedback_submit': 'கருத்தைச் சமர்ப்பிக்கவும்',
      'feedback_success': 'நன்றி! உங்கள் கருத்து பெறப்பட்டது.',
      'feedback_empty_error': 'சமர்ப்பிப்பதற்கு முன் செய்தியை உள்ளிடவும்.',
      'cancel_scan': 'ஸ்கேனை ரத்துசெய்க',
      'copy_summary_btn': 'சுருக்கத்தை நகலெடு',
      'summary_copied': 'நோயறிதல் சுருக்கம் கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது.',
      'share_other_apps': 'பிற பயன்பாடுகள் மூலம் பகிரவும்',
      'view_profile': 'சுயவிவரத்தைப் பார்க்கவும்',
      'back_to_home': 'முகப்புக்குத் திரும்பு',
      'low_confidence_badge': 'குறைந்த நம்பிக்கை பொருத்தம்',
      'add_photo_title': 'புதிய ஸ்கேன்',
      'add_photo_subtitle': 'AI நோயறிதலுக்கு பாதிக்கப்பட்ட தாவரத்தின் புகைப்படத்தை எடுக்கவும் அல்லது கேலரியிலிருந்து தேர்ந்தெடுக்கவும்.',
      'take_photo_btn': 'புகைப்படம் எடுக்கவும்',
      'take_photo_desc': 'இலையை ஸ்கேன் செய்ய கேமராவைப் பயன்படுத்தவும்',
      'choose_gallery_btn': 'கேலரியிலிருந்து தேர்வுசெய்க',
      'choose_gallery_desc': 'புகைப்பட நூலகத்திலிருந்து பதிவேற்றவும்',
      'supported_crops_label': 'ஆதரிக்கப்படும் பயிர்கள்',
      'supported_crops_desc': 'AI மாதிரி இந்த பயிர்களின் நோய்களை அடையாளம் காண பயிற்றுவிக்கப்பட்டுள்ளது:',
      'gallery_permission_denied_title': 'கேலரி அனுமதி தேவை',
      'gallery_permission_denied_desc': 'படங்களைத் தேர்ந்தெடுக்க பயன்பாட்டு அமைப்புகளில் புகைப்பட கேலரி அணுகலை வழங்கவும்.',
      'open_settings': 'அமைப்புகளைத் திறக்கவும்',
      'unknown_crop': 'தெரியாத பயிர்',
      'accessibility_title': 'அணுகல்தன்மை & காட்சி',
      'accessibility_subtitle': 'எழுத்து அளவு, மாறுபாடு, குரல் வேகம் மற்றும் ஆடியோ உதவியைத் தனிப்பயனாக்குங்கள்.',
      'accessibility_preview_title': 'நேரலை முன்னோட்டம்',
      'accessibility_sample_disease': 'தக்காளி ஆரம்பகால கருகல்',
      'accessibility_sample_advice': 'மேங்கோசெப் (2g/L) தெளித்து, பாதிக்கப்பட்ட கீழ் இலைகளை அகற்றவும்.',
      'section_display_text': 'காட்சி & உரை',
      'text_size': 'எழுத்து அளவு',
      'text_size_normal': 'இயல்பு (100%)',
      'text_size_medium': 'நடுத்தர (115%)',
      'text_size_large': 'பெரிய (130%)',
      'text_size_xlarge': 'மிகப் பெரிய (145%)',
      'high_contrast': 'உயர் மாறுபட்ட பயன்முறை',
      'high_contrast_desc': 'வெளிப்புற சூரிய ஒளியில் சிறந்த தெரிவுநிலைக்கு வண்ணங்கள் மற்றும் எல்லைகளை மேம்படுத்தவும்.',
      'section_voice_audio': 'குரல் & ஆடியோ (TTS)',
      'auto_read_diagnosis': 'தானியங்கி ஆடியோ வாசிப்பு',
      'auto_read_desc': 'நோய் கண்டறிதல் முடிவுகள் தோன்றும்போது குரல் சிகிச்சை வழிகாட்டலைத் தானாக இயக்கவும்.',
      'speech_rate': 'குரல் வேகம்',
      'speech_rate_slow': 'மெதுவாக',
      'speech_rate_normal': 'இயல்பு',
      'speech_rate_fast': 'வேகமாக',
      'test_voice_btn': 'குரலைச் சோதிக்கவும்',
      'test_voice_sample': 'வணக்கம்! CropCare உங்கள் பயிர் சிகிச்சை வழிகாட்டலை இவ்வாறு வாசிக்கும்.',
      'haptic_feedback': 'அதிர்வு பின்னூட்டம்',
      'haptic_feedback_desc': 'கேமரா பிடிப்பு மற்றும் நோய் கண்டறிதல் நிறைவில் அதிர்வுகளை வழங்கவும்.',
      'reset_defaults': 'இயல்புநிலைக்கு மீட்டமை',
      'section_offline': 'ஆஃப்லைன்',
      'offline_title': 'ஆஃப்லைன் & சேமிப்பகம்',
      'offline_subtitle': 'ஒத்திசைவு நிலை, தானியங்கி ஒத்திசைவு மற்றும் உள்ளூர் தரவு',
      'sync_status_title': 'கிளவுட் ஒத்திசைவு நிலை',
      'sync_all_synced': 'அனைத்து ஸ்கேன்களும் கிளவுட்டில் காப்புப் பிரதி எடுக்கப்பட்டுள்ளன',
      'sync_pending_count': 'ஸ்கேன்கள் ஒத்திசைக்கக் காத்திருக்கின்றன',
      'auto_sync_title': 'தானியங்கி ஒத்திசைவு',
      'auto_sync_desc': 'இணைய இணைப்பு கண்டறியப்பட்டதும் தானாகவே ஸ்கேன்களைப் பதிவேற்றவும்.',
      'delete_local_scans_title': 'உள்ளூர் ஸ்கேன்களை நீக்கு',
      'delete_local_scans_desc': 'இந்த சாதனத்திலிருந்து அனைத்து ஸ்கேன் படங்கள் மற்றும் வரலாற்றை அழித்து நினைவகத்தை விடுவிக்கவும்.',
      'delete_scans_confirm_title': 'உள்ளூர் ஸ்கேன்களை நீக்கவா?',
      'delete_scans_confirm_msg': 'இது இந்த சாதனத்தில் சேமிக்கப்பட்டுள்ள அனைத்து ஸ்கேன்களையும் நோய் கண்டறிதல் பதிவுகளையும் நீக்கும். இதை மாற்ற முடியாது.',
      'unsynced_warning_title': 'எச்சரிக்கை: ஒத்திசைக்கப்படாத ஸ்கேன்கள்',
      'unsynced_warning_msg': 'உங்கள் கணக்கில் இன்னும் ஒத்திசைக்கப்படாத ஸ்கேன்கள் உள்ளன. இப்போது அவற்றை நீக்கினால் அவை நிரந்தரமாக இழக்கப்படும்.',
      'sync_first_btn': 'முதலில் ஒத்திசைக்கவும்',
      'delete_anyway_btn': 'இருப்பினும் நீக்கு',
      'all_scans_deleted': 'அனைத்து உள்ளூர் ஸ்கேன்களும் நீக்கப்பட்டன.',
    },
  };

  static String get(String key, String languageCode) {
    final map = _localizedValues[languageCode] ?? _localizedValues['en']!;
    return map[key] ?? _localizedValues['en']![key] ?? key;
  }
}
