class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'CropCare',
      'splash_subtitle': 'Smart Crop Health Companion',
      'onboarding_title_1': 'Spot the problem',
      'onboarding_desc_1':
          'Take photos of diseased leaves or stems to detect crop issues early.',
      'onboarding_title_2': 'Get understandable guidance',
      'onboarding_desc_2':
          'Receive clear, actionable treatment instructions in your preferred language.',
      'onboarding_title_3': 'Get expert help when AI isn\'t confident',
      'onboarding_desc_3':
          'Connect with agricultural experts whenever automated diagnosis needs verification.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'select_language_title': 'Select Your Language',
      'select_language_subtitle': 'Choose your preferred language for CropCare',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල (Sinhala)',
      'lang_tamil': 'தமிழ் (Tamil)',
      'confirm': 'Confirm',
      'home_title': 'CropCare Home',
      'home_welcome': 'Welcome to CropCare!',
      'change_language': 'Change Language',
      'select_crop_title': 'Select Crop',
      'select_crop_subtitle': 'Choose the crop you want to scan',
      'camera_permission_title': 'Camera Permission Needed',
      'camera_permission_desc':
          'CropCare needs access to your camera to capture photos of crop leaves and stems for disease diagnosis.',
      'open_app_settings': 'Open App Settings',
      'grant_permission': 'Grant Permission',
      'capture_photo': 'Take Photo',
      'review_photo_title': 'Review Photo',
      'retake': 'Retake',
      'use_photo': 'Use Photo',
      'scan_result_title': 'Scan Details',
      'scan_id': 'Scan ID',
      'crop': 'Crop',
      'image_path': 'Image Path',
      'status': 'Status',
      'captured_at': 'Captured At',
      'settings_title': 'Settings',
      'section_language': 'Language',
      'section_accessibility': 'Accessibility',
      'section_notifications': 'Notifications',
      'section_offline_data': 'Offline Data',
      'coming_soon': 'Coming Soon',
      'coming_soon_desc': 'This feature will be available in a future update.',
      'start_scan': 'Scan Crop',
    },
    'si': {
      'app_title': 'CropCare',
      'splash_subtitle': 'ස්මාර්ට් බෝග සෞඛ්‍ය සහකාර',
      'onboarding_title_1': 'ගැටලුව හඳුනාගන්න',
      'onboarding_desc_1':
          'බෝග වල රෝග කල්තියා හඳුනා ගැනීමට ඡායාරූප ලබා ගන්න.',
      'onboarding_title_2': 'පැහැදිලි උපදෙස් ලබාගන්න',
      'onboarding_desc_2':
          'ඔබගේ භාෂාවෙන් පැහැදිලි ප්‍රතිකාර උපදෙස් ලබා ගන්න.',
      'onboarding_title_3': 'විශේෂඥ සහාය ලබාගන්න',
      'onboarding_desc_3':
          'AI පද්ධතියට විශ්වාස නැති විට කෘෂිකාර්මික විශේෂඥයින්ගේ සහාය ලබා ගන්න.',
      'skip': 'මගහරින්න',
      'next': 'ඊළඟ',
      'get_started': 'ආරම්භ කරන්න',
      'select_language_title': 'ඔබේ භාෂාව තෝරන්න',
      'select_language_subtitle': 'CropCare සඳහා ඔබ කැමති භාෂාව තෝරන්න',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'තහවුරු කරන්න',
      'home_title': 'CropCare මුල් පිටුව',
      'home_welcome': 'CropCare වෙත සාදරයෙන් පිළිගනිමු!',
      'change_language': 'භාෂාව වෙනස් කරන්න',
      'select_crop_title': 'බෝගය තෝරන්න',
      'select_crop_subtitle': 'ඔබට පරීක්ෂා කිරීමට අවශ්‍ය බෝගය තෝරන්න',
      'camera_permission_title': 'කැමරා අවසරය අවශ්‍යයි',
      'camera_permission_desc':
          'බෝග රෝග හඳුනා ගැනීම සඳහා කැමරාව භාවිත කිරීමට CropCare හට අවසර අවශ්‍ය වේ.',
      'open_app_settings': 'යෙදුම් සැකසීම් විවෘත කරන්න',
      'grant_permission': 'අවසර දෙන්න',
      'capture_photo': 'ඡායාරූපයක් ගන්න',
      'review_photo_title': 'ඡායාරූපය සමාලෝචනය කරන්න',
      'retake': 'නැවත ගන්න',
      'use_photo': 'ඡායාරූපය භාවිතා කරන්න',
      'scan_result_title': 'පරික්ශණ විස්තර',
      'scan_id': 'ස්කෑන් අංකය',
      'crop': 'බෝගය',
      'image_path': 'රූප මාර්ගය',
      'status': 'තත්ත්වය',
      'captured_at': 'ලබාගත් වේලාව',
      'settings_title': 'සැකසීම්',
      'section_language': 'භාෂාව',
      'section_accessibility': 'ප්‍රවේශ්‍යතාව',
      'section_notifications': 'දැනුම්දීම්',
      'section_offline_data': 'නොබැඳි දත්ත',
      'coming_soon': 'ළඟදීම',
      'coming_soon_desc': 'මෙම විශේෂාංගය ළඟදීම ලබා ගත හැක.',
      'start_scan': 'බෝගය පරීක්ෂා කරන්න',
    },
    'ta': {
      'app_title': 'CropCare',
      'splash_subtitle': 'ஸ்மார்ட் பயிர் சுகாதார உதவியாளர்',
      'onboarding_title_1': 'பிரச்சனையைக் கண்டறியவும்',
      'onboarding_desc_1':
          'பயிர் நோய்களை முன்கூட்டியே கண்டறிய புகைப்படங்களை எடுக்கவும்.',
      'onboarding_title_2': 'தெளிவான வழிகாட்டுதலைப் பெறுக',
      'onboarding_desc_2':
          'உங்கள் மொழியில் தெளிவான சிகிச்சை வழிமுறைகளைப் பெறுங்கள்.',
      'onboarding_title_3': 'நிபுணர் உதவியைப் பெறுங்கள்',
      'onboarding_desc_3':
          'AI பலவீனமாக இருக்கும் போது விவசாய நிபுணர்களின் உதவியைப் பெறுங்கள்.',
      'skip': 'தவிர்',
      'next': 'அடுத்து',
      'get_started': 'தொடங்கவும்',
      'select_language_title': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_language_subtitle':
          'CropCare க்கான உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'உறுதிப்படுத்து',
      'home_title': 'CropCare முகப்பு',
      'home_welcome': 'CropCare க்கு நல்வரவு!',
      'change_language': 'மொழியை மாற்றவும்',
      'select_crop_title': 'பயிரைத் தேர்ந்தெடுக்கவும்',
      'select_crop_subtitle':
          'நீங்கள் ஸ்கேன் செய்ய விரும்பும் பயிரைத் தேர்ந்தெடுக்கவும்',
      'camera_permission_title': 'கேமரா அனுமதி தேவை',
      'camera_permission_desc':
          'பயிர் நோய் கண்டறிதலுக்கு புகைப்படங்களை எடுக்க CropCare க்கு கேமரா அனுமதி தேவை.',
      'open_app_settings': 'பயன்பாட்டு அமைப்புகளைத் திறக்கவும்',
      'grant_permission': 'அனுமதி அளிக்கவும்',
      'capture_photo': 'புகைப்படம் எடுக்கவும்',
      'review_photo_title': 'புகைப்படத்தை மதிப்பாய்வு செய்யவும்',
      'retake': 'மீண்டும் எடுக்கவும்',
      'use_photo': 'புகைப்படத்தைப் பயன்படுத்தவும்',
      'scan_result_title': 'ஸ்கேன் விவரங்கள்',
      'scan_id': 'ஸ்கேன் ஐடி',
      'crop': 'பயிர்',
      'image_path': 'படப் பாதை',
      'status': 'நிலை',
      'captured_at': 'எடுக்கப்பட்ட நேரம்',
      'settings_title': 'அமைப்புகள்',
      'section_language': 'மொழி',
      'section_accessibility': 'அணுகல்தன்மை',
      'section_notifications': 'அறிவிப்புகள்',
      'section_offline_data': 'ஆஃப்லைன் தரவு',
      'coming_soon': 'விரைவில்',
      'coming_soon_desc': 'இந்த அம்சம் விரைவில் கிடைக்கும்.',
      'start_scan': 'பயிரைச் சோதிக்கவும்',
    },
  };

  static String get(String key, String languageCode) {
    final map = _localizedValues[languageCode] ?? _localizedValues['en']!;
    return map[key] ?? _localizedValues['en']![key] ?? key;
  }
}
