class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'CropCare',
      'splash_subtitle': 'Smart Crop Health Companion',
      'onboarding_title_1': 'Spot the problem',
      'onboarding_desc_1':
          'Take photos of diseased leaves or stems to detect crop issues early.',
      'onboarding_title_2': 'Get understandable guidance',
      'onboarding_desc_2':
          'Receive clear, actionable treatment instructions in your preferred language.',
      'onboarding_title_3': 'Get expert help when AI isn\'t confident',
      'onboarding_desc_3':
          'Connect with agricultural experts whenever automated diagnosis needs verification.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'select_language_title': 'Select Your Language',
      'select_language_subtitle': 'Choose your preferred language for CropCare',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල (Sinhala)',
      'lang_tamil': 'தமிழ் (Tamil)',
      'confirm': 'Confirm',
      'home_title': 'CropCare Home',
      'home_welcome': 'Welcome to CropCare!',
      'change_language': 'Change Language',
      'select_crop_title': 'Select Crop',
      'select_crop_subtitle': 'Choose the crop you want to scan',
      'camera_permission_title': 'Camera Permission Needed',
      'camera_permission_desc':
          'CropCare needs access to your camera to capture photos of crop leaves and stems for disease diagnosis.',
      'open_app_settings': 'Open App Settings',
      'grant_permission': 'Grant Permission',
      'capture_photo': 'Take Photo',
      'review_photo_title': 'Review Photo',
      'retake': 'Retake',
      'use_photo': 'Use Photo',
      'scan_result_title': 'Scan Details',
      'scan_id': 'Scan ID',
      'crop': 'Crop',
      'image_path': 'Image Path',
      'status': 'Status',
      'captured_at': 'Captured At',
      'settings_title': 'Settings',
      'section_language': 'Language',
      'section_accessibility': 'Accessibility',
      'section_notifications': 'Notifications',
      'section_offline_data': 'Offline Data',
      'coming_soon': 'Coming Soon',
      'coming_soon_desc': 'This feature will be available in a future update.',
      'start_scan': 'Scan Crop',
      'diagnosis_result_title': 'Diagnosis Result',
      'treatment_guidance_title': 'Treatment Guidance',
      'treatment_summary': 'Summary',
      'treatment_what_to_do': 'What to Do',
      'treatment_what_to_avoid': 'What to Avoid',
      'recheck_after_days': 'Recheck in',
      'days': 'days',
      'treatment_source_llm': 'AI-generated advice (Gemini)',
      'treatment_observations_label': 'Add observations (Optional)',
      'treatment_observations_hint':
          'e.g. Started 3 days ago, leaves turning yellow from bottom, watered daily...',
      'get_treatment_btn': 'Get AI Recommendation',
      'offline_connection_msg':
          'Cannot reach CropCare AI. Please check your internet or Wi-Fi connection.',
      'retry_btn': 'Retry',
      'healthy_crop_msg':
          'Your plant appears healthy! Keep up your current crop management practices.',
      'ai_disclaimer':
          'AI-assisted prediction — verify before extensive chemical application.',
      'scan_again': 'Scan Again',
      'get_expert_help': 'WhatsApp Share with Expert',
      'disease_detected': 'Disease Detected',
      'confidence': 'Confidence',
      'severity': 'Severity',
      'fetching_treatment': 'Consulting AI Agronomist...',
      'low_confidence_advisory':
          'Low confidence AI result (<80%). We suggest consulting an agricultural expert via WhatsApp.',
      'escalation_title': 'Escalate to Expert',
      'escalation_subtitle':
          'Share leaf photo and diagnosis details with an agronomist on WhatsApp',
      'farmer_notes_label': 'Observations / Notes for Expert',
      'farmer_notes_hint':
          'e.g. Field location, duration of symptoms, fertilizer used...',
      'share_whatsapp_btn': 'Share via WhatsApp with Expert',
      'scan_history_title': 'Scan History',
      'scan_history_empty':
          'No scans yet. Tap "Scan Crop" above to start your first diagnosis!',
      'filter_all': 'All',
      'filter_low_conf': 'Low Confidence',
      'filter_shared': 'Shared',
      'filter_healthy': 'Healthy',
      'scans_count': 'scans',
    },
    'si': {
      'app_title': 'CropCare',
      'splash_subtitle': 'ස්මාර්ට් බෝග සෞඛ්‍ය සහකාර',
      'onboarding_title_1': 'ගැටලුව හඳුනාගන්න',
      'onboarding_desc_1':
          'බෝග වල රෝග කල්තියා හඳුනා ගැනීමට ඡායාරූප ලබා ගන්න.',
      'onboarding_title_2': 'පැහැදිලි උපදෙස් ලබාගන්න',
      'onboarding_desc_2':
          'ඔබගේ භාෂාවෙන් පැහැදිලි ප්‍රතිකාර උපදෙස් ලබා ගන්න.',
      'onboarding_title_3': 'විශේෂඥ සහාය ලබාගන්න',
      'onboarding_desc_3':
          'AI පද්ධතියට විශ්වාස නැති විට කෘෂිකාර්මික විශේෂඥයින්ගේ සහාය ලබා ගන්න.',
      'skip': 'මගහරින්න',
      'next': 'ඊළඟ',
      'get_started': 'ආරම්භ කරන්න',
      'select_language_title': 'ඔබේ භාෂාව තෝරන්න',
      'select_language_subtitle': 'CropCare සඳහා ඔබ කැමති භාෂාව තෝරන්න',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'තහවුරු කරන්න',
      'home_title': 'CropCare මුල් පිටුව',
      'home_welcome': 'CropCare වෙත සාදරයෙන් පිළිගනිමු!',
      'change_language': 'භාෂාව වෙනස් කරන්න',
      'select_crop_title': 'බෝගය තෝරන්න',
      'select_crop_subtitle': 'ඔබට පරීක්ෂා කිරීමට අවශ්‍ය බෝගය තෝරන්න',
      'camera_permission_title': 'කැමරා අවසරය අවශ්‍යයි',
      'camera_permission_desc':
          'බෝග රෝග හඳුනා ගැනීම සඳහා කැමරාව භාවිත කිරීමට CropCare හට අවසර අවශ්‍ය වේ.',
      'open_app_settings': 'යෙදුම් සැකසීම් විවෘත කරන්න',
      'grant_permission': 'අවසර දෙන්න',
      'capture_photo': 'ඡායාරූපයක් ගන්න',
      'review_photo_title': 'ඡායාරූපය සමාලෝචනය කරන්න',
      'retake': 'නැවත ගන්න',
      'use_photo': 'ඡායාරූපය භාවිතා කරන්න',
      'scan_result_title': 'පරික්ශණ විස්තර',
      'scan_id': 'ස්කෑන් අංකය',
      'crop': 'බෝගය',
      'image_path': 'රූප මාර්ගය',
      'status': 'තත්ත්වය',
      'captured_at': 'ලබාගත් වේලාව',
      'settings_title': 'සැකසීම්',
      'section_language': 'භාෂාව',
      'section_accessibility': 'ප්‍රවේශ්‍යතාව',
      'section_notifications': 'දැනුම්දීම්',
      'section_offline_data': 'නොබැඳි දත්ත',
      'coming_soon': 'ළඟදීම',
      'coming_soon_desc': 'මෙම විශේෂාංගය ළඟදීම ලබා ගත හැක.',
      'start_scan': 'බෝගය පරීක්ෂා කරන්න',
      'diagnosis_result_title': 'රෝග නිර්ණය ප්‍රතිඵලය',
      'treatment_guidance_title': 'ප්‍රතිකාර මාර්ගෝපදේශය',
      'treatment_summary': 'සාරාංශය',
      'treatment_what_to_do': 'කළ යුතු දේ',
      'treatment_what_to_avoid': 'නොකළ යුතු දේ',
      'recheck_after_days': 'නැවත පරීක්ෂා කරන්න',
      'days': 'දිනකින්',
      'treatment_source_llm': 'AI මගින් ජනනය කරන ලද උපදෙස්',
      'treatment_observations_label': 'ඔබගේ නිරීක්ෂණ ඇතුළත් කරන්න (අවශ්‍ය නම් පමණි)',
      'treatment_observations_hint':
          'උදා: දින 3කට පෙර ආරම්භ විය, පහළ කොළ කහ පැහැ වේ, වර්ෂාව ලැබුණි...',
      'get_treatment_btn': 'AI නිර්දේශ ලබාගන්න',
      'offline_connection_msg':
          'CropCare AI සම්බන්ධ කරගත නොහැක. කරුණාකර ඔබගේ අන්තර්ජාල හෝ Wi-Fi සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'retry_btn': 'නැවත උත්සාහ කරන්න',
      'healthy_crop_msg':
          'ඔබේ ශාකය නිරෝගීව පෙනේ! නිසි වගා පිළිවෙත් දිගටම කරගෙන යන්න.',
      'ai_disclaimer':
          'AI මගින් උපකල්පනය කරන ලද්දකි — රසායනික ද්‍රව්‍ය යෙදීමට පෙර තහවුරු කරගන්න.',
      'scan_again': 'නැවත ස්කෑන් කරන්න',
      'get_expert_help': 'විශේෂඥයෙකුට WhatsApp මගින් යවන්න',
      'disease_detected': 'හඳුනාගත් රෝගය',
      'confidence': 'විශ්වාසනීයත්වය',
      'severity': 'බරපතලකම',
      'fetching_treatment': 'AI කෘෂි විශේෂඥයාගෙන් උපදෙස් ලබාගනිමින්...',
      'low_confidence_advisory':
          'අඩු විශ්වාසනීයත්වයක් සහිත AI ප්‍රතිඵලයකි (<80%). කෘෂිකර්ම විශේෂඥයෙකුගෙන් විමසීමට නිර්දේශ කරමු.',
      'escalation_title': 'විශේෂඥ උපදෙස් ලබාගැනීම',
      'escalation_subtitle':
          'පත්‍රයේ ඡායාරූපය සහ රෝග විස්තර WhatsApp මගින් කෘෂි විශේෂඥයෙකුට යවන්න',
      'farmer_notes_label': 'විශේෂඥයා සඳහා ඔබේ නිරීක්ෂණ',
      'farmer_notes_hint':
          'උදා: වගා බිමේ පිහිටීම, රෝග ලක්ෂණ පැවති කාලය, යෙදූ පොහොර...',
      'share_whatsapp_btn': 'WhatsApp මගින් විශේෂඥයාට යවන්න',
      'scan_history_title': 'පසුගිය පරික්ශණ',
      'scan_history_empty':
          'තවමත් කිසිදු පරික්ශණයක් කර නොමැත. ආරම්භ කිරීමට "බෝගය පරීක්ෂා කරන්න" ඔබන්න!',
      'filter_all': 'සියල්ල',
      'filter_low_conf': 'අඩු විශ්වාසනීය',
      'filter_shared': 'යවන ලද',
      'filter_healthy': 'නිරෝගී',
      'scans_count': 'පරික්ශණ',
    },
    'ta': {
      'app_title': 'CropCare',
      'splash_subtitle': 'ஸ்மார்ட் பயிர் சுகாதார உதவியாளர்',
      'onboarding_title_1': 'பிரச்சனையைக் கண்டறியவும்',
      'onboarding_desc_1':
          'பயிர் நோய்களை முன்கூட்டியே கண்டறிய புகைப்படங்களை எடுக்கவும்.',
      'onboarding_title_2': 'தெளிவான வழிகாட்டுதலைப் பெறுக',
      'onboarding_desc_2':
          'உங்கள் மொழியில் தெளிவான சிகிச்சை வழிமுறைகளைப் பெறுங்கள்.',
      'onboarding_title_3': 'நிபுணர் உதவியைப் பெறுங்கள்',
      'onboarding_desc_3':
          'AI பலவீனமாக இருக்கும் போது விவசாய நிபுணர்களின் உதவியைப் பெறுங்கள்.',
      'skip': 'தவிர்',
      'next': 'அடுத்து',
      'get_started': 'தொடங்கவும்',
      'select_language_title': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_language_subtitle':
          'CropCare க்கான உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      'lang_english': 'English',
      'lang_sinhala': 'සිංහල',
      'lang_tamil': 'தமிழ்',
      'confirm': 'உறுதிப்படுத்து',
      'home_title': 'CropCare முகப்பு',
      'home_welcome': 'CropCare க்கு நல்வரவு!',
      'change_language': 'மொழியை மாற்றவும்',
      'select_crop_title': 'பயிரைத் தேர்ந்தெடுக்கவும்',
      'select_crop_subtitle':
          'நீங்கள் ஸ்கேன் செய்ய விரும்பும் பயிரைத் தேர்ந்தெடுக்கவும்',
      'camera_permission_title': 'கேமரா அனுமதி தேவை',
      'camera_permission_desc':
          'பயிர் நோய் கண்டறிதலுக்கு புகைப்படங்களை எடுக்க CropCare க்கு கேமரா அனுமதி தேவை.',
      'open_app_settings': 'பயன்பாட்டு அமைப்புகளைத் திறக்கவும்',
      'grant_permission': 'அனுமதி அளிக்கவும்',
      'capture_photo': 'புகைப்படம் எடுக்கவும்',
      'review_photo_title': 'புகைப்படத்தை மதிப்பாய்வு செய்யவும்',
      'retake': 'மீண்டும் எடுக்கவும்',
      'use_photo': 'புகைப்படத்தைப் பயன்படுத்தவும்',
      'scan_result_title': 'ஸ்கேன் விவரங்கள்',
      'scan_id': 'ஸ்கேன் ஐடி',
      'crop': 'பயிர்',
      'image_path': 'படப் பாதை',
      'status': 'நிலை',
      'captured_at': 'எடுக்கப்பட்ட நேரம்',
      'settings_title': 'அமைப்புகள்',
      'section_language': 'மொழி',
      'section_accessibility': 'அணுகல்தன்மை',
      'section_notifications': 'அறிவிப்புகள்',
      'section_offline_data': 'ஆஃப்லைன் தரவு',
      'coming_soon': 'விரைவில்',
      'coming_soon_desc': 'இந்த அம்சம் விரைவில் கிடைக்கும்.',
      'start_scan': 'பயிரைச் சோதிக்கவும்',
      'diagnosis_result_title': 'நோய் கண்டறிதல் முடிவு',
      'treatment_guidance_title': 'சிகிச்சை வழிகாட்டுதல்',
      'treatment_summary': 'சுருக்கம்',
      'treatment_what_to_do': 'செய்ய வேண்டியவை',
      'treatment_what_to_avoid': 'தவிர்க்க வேண்டியவை',
      'recheck_after_days': 'மீண்டும் பரிசோதிக்கவும்',
      'days': 'நாட்களில்',
      'treatment_source_llm': 'AI உருவாக்கிய ஆலோசனை',
      'treatment_observations_label': 'உங்கள் அவதானிப்புகளைச் சேர்க்கவும் (விருப்பத்திற்குரியது)',
      'treatment_observations_hint':
          'எ.கா. 3 நாட்களுக்கு முன் தொடங்கியது, கீழ் இலைகள் மஞ்சள் நிறமாகிறது...',
      'get_treatment_btn': 'AI பரிந்துரையைப் பெறுங்கள்',
      'offline_connection_msg':
          'CropCare AI உடன் இணைக்க முடியவில்லை. உங்கள் இணையம் அல்லது Wi-Fi இணைப்பைச் சரிபார்க்கவும்.',
      'retry_btn': 'மீண்டும் முயற்சிக்கவும்',
      'healthy_crop_msg':
          'உங்கள் பயிர் ஆரோக்கியமாகத் தெரிகிறது! வழக்கமான விவசாய முறைகளைத் தொடரவும்.',
      'ai_disclaimer':
          'AI உதவி முன்னறிவிப்பு — இரசாயனங்களைப் பயன்படுத்துவதற்கு முன் சரிபார்க்கவும்.',
      'scan_again': 'மீண்டும் ஸ்கேன் செய்யவும்',
      'get_expert_help': 'நிபுணருடன் WhatsApp இல் பகிரவும்',
      'disease_detected': 'கண்டறியப்பட்ட நோய்',
      'confidence': 'நம்பகத்தன்மை',
      'severity': 'தீவிரம்',
      'fetching_treatment': 'AI விவசாய நிபுணரிடம் ஆலோசனை பெறுகிறது...',
      'low_confidence_advisory':
          'குறைந்த நம்பகத்தன்மை கொண்ட AI முடிவு (<80%). வாட்ஸ்அப் மூலம் விவசாய நிபுணரிடம் ஆலோசனை பெற பரிந்துரைக்கிறோம்.',
      'escalation_title': 'நிபுணரிடம் பரிந்துரைக்கவும்',
      'escalation_subtitle':
          'இலை புகைப்படம் மற்றும் நோய் விவரங்களை வாட்ஸ்அப்பில் பகிரவும்',
      'farmer_notes_label': 'நிபுணருக்கான உங்கள் அவதானிப்புகள்',
      'farmer_notes_hint':
          'எ.கா. வயல் இருப்பிடம், அறிகுறிகள் நீடித்த காலம், பயன்படுத்திய உரம்...',
      'share_whatsapp_btn': 'WhatsApp மூலம் நிபுணருடன் பகிரவும்',
      'scan_history_title': 'முந்தைய ஸ்கேன்கள்',
      'scan_history_empty':
          'இதுவரை ஸ்கேன்கள் இல்லை. உங்கள் முதல் பரிசோதனையைத் தொடங்க மேலே உள்ள "பயிரைச் சோதிக்கவும்" என்பதைத் தட்டவும்!',
      'filter_all': 'அனைத்தும்',
      'filter_low_conf': 'குறைந்த நம்பகத்தன்மை',
      'filter_shared': 'பகிரப்பட்டது',
      'filter_healthy': 'ஆரோக்கியமானது',
      'scans_count': 'ஸ்கேன்கள்',
    },
  };

  static String get(String key, String languageCode) {
    final map = _localizedValues[languageCode] ?? _localizedValues['en']!;
    return map[key] ?? _localizedValues['en']![key] ?? key;
  }
}
